name: Test Coverage report
on:
  pull_request:
    branches:
      - main
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Enable Corepack
        run: corepack enable

      - name: Use Node 20
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Run install
        run: pnpm install

      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          package-manager: pnpm
          working-directory: lib
