name: Test Coverage report
on:
  pull_request:
    branches:
      - main
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Enable Corepack
        run: corepack enable

      - name: Use Node 20
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'yarn'

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          package-manager: yarn
          working-directory: lib
