name: CI
on: [push]
jobs:
  build:
    name: ESLint, Prettier, Type-check, and Build.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Enable corepack
        run: corepack enable

      - name: Use Node 20
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'yarn'

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Lint
        uses: borales/actions-yarn@v4
        with:
          cmd: lint

      - name: Formatting
        uses: borales/actions-yarn@v4
        with:
          cmd: prettier-check

      - name: type-check
        uses: borales/actions-yarn@v4
        with:
          cmd: type-check

      - name: Build
        uses: borales/actions-yarn@v4
        with:
          cmd: build
