name: CI
on: [push]
jobs:
  build:
    name: ESLint, Prettier, Type-check, and Build.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Enable corepack
        run: corepack enable

      - name: Use Node 20
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Run install
        run: pnpm install

      - name: ESLint
        run: pnpm lint

      - name: Prettier
        run: pnpm prettier-check

      - name: Type-check
        run: pnpm type-check

      - name: Build
        run: pnpm build
