name: Size Limit report
on:
  pull_request:
    branches:
      - main
jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Enable Corepack
        run: corepack enable

      - name: Use Node 20
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Run install
        run: pnpm install

      - name: Runs size-limit
        uses: andresz1/size-limit-action@v1.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          package_manager: pnpm
          build_script: --filter fetchtastic build
          script: pnpm size
          skip_step: install
