name: Size limit report
on:
  pull_request:
    branches:
      - main
jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Runs size-limit
        uses: andresz1/size-limit-action@v1.7.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          package_manager: yarn
          build_script: yarn workspace xshield build
          script: yarn workspace xshield size --json
          
